version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always


