version: '3.8'
services:

  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    env_file:
      - .env.prod
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mynet
    restart: always

  api-go:
    build: .
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge
